services:
  mongodb:
    container_name: oai-agents-db
    image: mongo:8
    restart: always
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oaiAgents123
    volumes:
      - db_data:/data/db

volumes:
  db_data:
